import pandas as pd
import json
from datetime import datetime
from pathlib import Path
from src import config


AUDIT_LOG_PATH = config.OUTPUTS_DIR / "audit_trail.csv"
SAR_DIR = config.OUTPUTS_DIR / "SAR_reports"


def _init_audit_log():
    """Create audit log CSV if it doesn't exist."""
    if not AUDIT_LOG_PATH.exists():
        pd.DataFrame(columns=[
            "timestamp", "account_idx", "action",
            "risk_tier", "risk_score", "investigator",
            "reason", "status"
        ]).to_csv(AUDIT_LOG_PATH, index=False)


def log_action(account_idx: int, action: str, risk_tier: str,
               risk_score: float, investigator: str = "System",
               reason: str = ""):
    """
    Log an investigator action to the audit trail CSV.

    Actions: FREEZE, FLAG_FOR_REVIEW, CLEAR, ESCALATE, MONITOR
    """
    _init_audit_log()

    new_row = {
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "account_idx": account_idx,
        "action": action,
        "risk_tier": risk_tier,
        "risk_score": round(risk_score, 4),
        "investigator": investigator,
        "reason": reason,
        "status": "PENDING" if action in ["FREEZE", "ESCALATE"] else "CLOSED"
    }

    existing = pd.read_csv(AUDIT_LOG_PATH)
    updated = pd.concat([existing, pd.DataFrame([new_row])], ignore_index=True)
    updated.to_csv(AUDIT_LOG_PATH, index=False)

    return new_row


def generate_sar(account_idx: int, risk_score: float, risk_tier: str,
                 xgb_proba: float, drivers: list, report_text: str):
    """
    Generate a Suspicious Activity Report (SAR) for a frozen/escalated account.
    Saved as a structured text file in outputs/SAR_reports/.
    """
    SAR_DIR.mkdir(parents=True, exist_ok=True)

    sar_path = SAR_DIR / f"SAR_account_{account_idx}.txt"
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    drivers_text = "\n".join([
        f"  {i+1}. {d['feature']}: {d['shap_value']:.4f} ({d['direction']})"
        for i, d in enumerate(drivers)
    ])

    sar_content = f"""
╔══════════════════════════════════════════════════════════╗
║         SUSPICIOUS ACTIVITY REPORT (SAR)                ║
╚══════════════════════════════════════════════════════════╝

Generated: {timestamp}
Report ID: SAR-{account_idx}-{datetime.now().strftime('%Y%m%d')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
ACCOUNT DETAILS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Account Index  : {account_idx}
Risk Tier      : {risk_tier}
Risk Score     : {risk_score:.4f} / 1.0000
XGBoost Prob   : {xgb_proba:.4f}
Status         : UNDER INVESTIGATION

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
AI RISK DRIVERS (SHAP ANALYSIS)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{drivers_text}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
AI INVESTIGATION NOTE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{report_text}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
RECOMMENDED ACTIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1. Freeze account immediately pending investigation
2. Request KYC re-verification from account holder
3. Review last 90 days of transaction history
4. Cross-reference with I4C cyber fraud complaint database
5. Report to RBI Financial Intelligence Unit if confirmed

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
COMPLIANCE NOTES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
This report was generated by the AI Mule Detection System.
All actions must be reviewed and approved by a certified
compliance officer before execution.
Reference: RBI Master Direction on KYC (2016), PMLA 2002

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""

    with open(sar_path, "w", encoding="utf-8") as f:
        f.write(sar_content)

    return sar_path


def get_audit_trail() -> pd.DataFrame:
    """Load and return the full audit trail."""
    _init_audit_log()
    return pd.read_csv(AUDIT_LOG_PATH)


def get_account_status(account_idx: int) -> str:
    """Get the latest action status for an account."""
    _init_audit_log()
    df = pd.read_csv(AUDIT_LOG_PATH)
    account_logs = df[df["account_idx"] == account_idx]
    if account_logs.empty:
        return "NO_ACTION"
    return account_logs.iloc[-1]["action"]